# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0002_auto_20170523_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='django_books.Author'),
        ),
    ]
